name: Build and Deploy Examples

on:
  push:
    branches:
    - examples-next

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install, lint, and build
      run: |
        npm install
        npm run build

    - name: Deploy to s3
      env:
        AWS_DEFAULT_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 sync dist s3://phila-ui-examples-next --region us-east-1 --delete