name: Build and Deploy Any Branch

on:
  push:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EthanSK/git-branch-name-action@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: npm install
        run: |
          npm install
          [ ! -d "node_modules/@phila/phila-ui/dist/" ] && cd node_modules/@phila/phila-ui/ && npm install && npm run build && rm -rf node_modules && cd ../../../
      - name: build branch (skip examples, beta)
        if: ${{ env.GIT_BRANCH_NAME != 'examples' && env.GIT_BRANCH_NAME != 'beta' }}
        run: |
          export VUE_APP_GIT_BRANCH=${GIT_BRANCH_NAME};  npm run build --prod
      - name: build examples or beta
        if: ${{ env.GIT_BRANCH_NAME == 'examples' || env.GIT_BRANCH_NAME == 'beta' }}
        run: |
          npm run build --prod
      - name: Deploy Beta
        if: ${{ env.GIT_BRANCH_NAME == 'beta' }}
        env:
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync dist s3://${{ secrets.AWS_BUCKET_BETA }} --region us-east-1 --delete
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DIST_BETA }} --paths "/*"
      - name: Deploy Examples
        if: ${{ env.GIT_BRANCH_NAME == 'examples' }}
        env:
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync dist s3://${{ secrets.AWS_BUCKET_EXAMPLES }} --region us-east-1 --delete
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DIST_EXAMPLES }} --paths "/*"
      - name: Deploy Other Branch
        if: ${{ env.GIT_BRANCH_NAME != 'examples' && env.GIT_BRANCH_NAME != 'beta' }}
        env:
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync dist s3://${{ secrets.AWS_PARENT_BUCKET }}/${GIT_BRANCH_NAME} --region us-east-1 --delete